### ISSUE TITLE
aaftf filter URL issue

### ISSUE THREAD

**Issue by Bambi3024** [stajichlab/AAFTF#28]
Hello! I tried to run the script for aaftf filter but terminal gave me always the same error:
Running AAFTF v0.5.0
 error with url https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/819/615/GCF_000819615.1_ViralProj14015/GCF_000819615.1_ViralProj14015_genomic.fna.gz aaftf-filter_85caa12f/GCF_000819615.1_ViralProj14015_genomic.fna.gz
Traceback (most recent call last):
  File "/mnt/home/dematth2/anaconda3/envs/aaftf/bin/AAFTF", line 8, in <module>
    sys.exit(main())
  File "/mnt/home/dematth2/anaconda3/envs/aaftf/lib/python3.7/site-packages/AAFTF/AAFTF_main.py", line 1113, in main
    args.func(parser, args)
  File "/mnt/home/dematth2/anaconda3/envs/aaftf/lib/python3.7/site-packages/AAFTF/AAFTF_main.py", line 53, in run_subtool
    submodule.run(parser, args)
  File "/mnt/home/dematth2/anaconda3/envs/aaftf/lib/python3.7/site-packages/AAFTF/filter.py", line 65, in run
    earliest_file_age = os.path.getctime(acc_file)
  File "/mnt/home/dematth2/anaconda3/envs/aaftf/lib/python3.7/genericpath.py", line 65, in getctime
    return os.stat(filename).st_ctime
FileNotFoundError: [Errno 2] No such file or directory: 'aaftf-filter_85caa12f/GCF_000819615.1_ViralProj14015_genomic.fna.gz'
======= This is where my script ends! =========

I tried to modify the link because, if i delete the last part and i copy on my internet page i can download the Escherichia coli's sequence but never has changed on the terminal...i obtained the same error.
I tried also to modify the script first by adding the genome directory (before i downloaded it) with the options -u  but it keeps insisting on the URL and then i tried to add the right URL instead, but it keeps giving an error on that initial URL. 

Thank you 👍

**Comment by hyphaltip** [comment]
I’ll see why the downloads may have an issue. You can also download manually.

**Comment by Bambi3024** [comment]
Thank you. Is there a manual, or a more detailed documentation, for this pipeline I can use? Or maybe is it included in a publication?
Thanks again,
Martina

**Comment by mcmurtrs** [comment]
Hello,

I have been getting various errors on the filtering step as well. I have tried unistalling and reinstalling AFFTF. The most recent issue (please see below) is that it says it is outputting the filtered reads into a new directory but there are no files present in the directory. Is there additional documentation available for troubleshooting? 

~/conda/miniconda3/bin/AAFTF filter --left AKC434_trimmed_1P.fastq.gz --right AKC434_trimmed_2P.fastq.gz -o /filter_reads/AKC434_filtered
[Dec 11 08:38 AM] Running AAFTF v0.5.0
[Dec 11 08:38 AM] Generating combined contamination database aaftf-filter_f9e2f19d/contamdb.fa from:
aaftf-filter_f9e2f19d/GCF_000819615.1_ViralProj14015_genomic.fna.gz
aaftf-filter_f9e2f19d/UniVec
[Dec 11 08:38 AM] Loading 24,172,990 total reads
[Dec 11 08:38 AM] Kmer filtering reads using BBDuk
CMD: bbduk.sh -Xmx302g t=1 hdist=1 k=27 overwrite=true
        in=AKC434_trimmed_1P.fastq.gz
        out=/filter_reads/AKC434_filtered_1.fastq.gz
        in2=/nfs7/McMurtrey_Lab/2024_sequences/L1-dual-8bp-1mm/trimmed_reads2
        out2=/filter_reads/AKC434_filtered_2.fastq.gz ref=aaftf-
        filter_f9e2f19d/contamdb.fa,phix,artifacts,lambda
[Dec 11 08:40 AM] 24,172,990 reads mapped to contamination database
[Dec 11 08:40 AM] 0 reads unmapped and writing to file
[Dec 11 08:40 AM] Filtering complete:
        For: /filter_reads/AKC434_REDO_filtered_filtered_1.fastq.gz
        Rev: /filter_reads/AKC434_REDO_filtered_filtered_2.fastq.gz
[Dec 11 08:40 AM] Your next command might be:
        AAFTF assemble -l AKC434_REDO_filtered_filtered_1.fastq.gz -r AKC434_REDO_filtered_filtered_2.fastq.gz -c 1 -o /filter_reads/AKC434.spades.fasta

**Comment by hyphaltip** [comment]
I assume ' /filter_reads/' is writable? Usually top level partition
folders are not?

But either way the tool is tellingyou all the reads are contamination:

[Dec 11 08:40 AM] 24,172,990 reads mapped to contamination database


---
Jason Stajich, PhD
Professor, Department of Microbiology and Plant Pathology
University of California, Riverside
Fellow, CIFAR Fungal Kingdom: Threats and Opportunities
<https://www.cifar.ca/research/program/fungal-kingdom>
email: ***@***.***
bluesky: @hyphaltip.bsky.social twitter: @stajichlab
<http://twitter.com/stajichlab> @hyphaltip <http://twitter.com/hyphaltip> @
zygolife <http://twitter.com/zygolife> mastadon: @hyphaltip
***@***.***>
website: https://lab.stajich.org github: stajichlab
<https://github.com/stajichlab>
office: +1 951.827.2363 mobile: +1 909.333.6709
